service:
  name: get-abo-los-maps
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  profile: cc-profile

package:
  include:
    - dist/**
  exclude:
    - node_modules/**

functions:
  get-abo-los-maps:
    handler: src/handler.aboLosMapGet
    events:
      - http:
          method: get
          path: "dms/{market}?affAbo[]={affiliatecode}&period[]={period}&/&includeMap=true&includeAboAttr=true"
          headers:
            - Authorization
